version: "3.3"

services:
    myphp:
        build: ./src/php
        container_name: myphp
        ports:
            - "9000:9000"
        restart: always
        volumes:
            - $HOME/cca2/src:/var/www/html
        networks:
            - mynet
    mynginx:
        depends_on:
            - myphp
        image: nginx:latest
        container_name: mynginx
        ports:
            - "8080:80"
        restart: always
        volumes:
            - $HOME/cca2/src:/var/www/html
            - $HOME/cca2/src/nginx.ini:/etc/nginx/conf.d/default.conf
        links:
            - "myphp:myphp"
        networks:
            - mynet
networks:
        mynet:
            driver: bridge
